# Generated by Django 5.0.6 on 2026-08-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('discogs_import', 'Discogs Import'), ('user_created', 'User Created')], max_length=20)),
            ],
        ),
    ]
