# Generated by Django 5.0.6 on 2026-08-30 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discogs_release_id', models.PositiveIntegerField()),
                ('catalog_number', models.CharField(blank=True, default='', max_length=100)),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=255)),
                ('personal_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('released_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('collection', 'Collection')], max_length=20)),
                ('date_added', models.DateTimeField()),
                ('media_condition', models.CharField(blank=True, choices=[('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Very Good Plus', 'Very Good Plus'), ('Very Good', 'Very Good'), ('Good Plus', 'Good Plus'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('sleeve_condition', models.CharField(blank=True, choices=[('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Very Good Plus', 'Very Good Plus'), ('Very Good', 'Very Good'), ('Good Plus', 'Good Plus'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cover_art_url', models.URLField(blank=True, default='')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='tracker.folder')),
            ],
        ),
    ]
