# Generated by Django 5.0.6 on 2026-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
