# Generated by Django 5.0.6 on 2026-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_release_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='num_for_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
